language: ruby
rvm:
 - 2.4.1
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  organization: development-ccsong
  space: development
  on:
    branch: master
  username:
    secure: VW5bRoEjYNgzHESDZmVa2cwop0iJavNcUu6ukXilYTA6hXN5MQQqnhyjIG1sGwhwca5U4vdRi9mMEhP2Hy/Y5/riKvNHJ3WYMPAYErdyPK0C5m5aFfLrt1txWJlhadLxoUiwRpIdqCwEZYJ7N/sPNmmvAprVYRUgc9IMmHBxLjH+wdfAJBZSn0HAAKm7qVQ8z70g0Fz+VoXyzui+xw1riD7BpkcKbExwHIB3AfgEiyJ4X5PBpD643e8Fgk0khGcYYPvWElaPuYIbIAy7WoN1CFMDkXadS8UviasFq8Dk0wELAkR8FOcYZpzmz5kQTcMSMEz3p3jkmAnnpERC/4wSH2d7GMW0hP8e/V+JbvUBieTW+Hpzz0BnN4WOIsS5HsF3CP6xOLlZZGujL2yS1J7vNPLXNZcEanoCbRkrozOjD2h3kQvzSU5bnqSuyK05k5DNnj41vso8advEADdMyDXHuL5twGau4JWVIUUDwWOqRMt3HmV1+j8DxOS8jpjYtiwE4H9LUlXaDSKdDhwQMwV2z0N79olfd8rUmO4fbD7gypqLfnnuss8oTFZ9iFa4b2K7uxGturET69ew6G4VPqkrStY1HxBiHrpkcDG0BcNwkLoekhcHlZTulviN26wHhwR5XjPX/Qd8Xo6oO4vk0avFKBI0Wza2Xm3IzahHtVjjc5o=
  password:
    secure: FLbTRGdx0wpodWw4nc+GucczzwNM+ZAQujDruBImhiIxm/BewLQ4EDmfdblk6+clo6KxbifybksO14sd1Fsg3MT2d+89LpxofwHQDDrEWCMQ1Mgj5yyPPK5onfknnseXthc0JRPUp+nzsyQBvHKR5Z+ANJ/aCy+aKVHGdr55FOhxYbDpwPHkGLLnLvk3MGB6gLzznoeuO/QXlmmVtCcV1fWTLy9t6ymPn8nJHEFf9FeiMbDkCoTxuwx8cUxIlhIJ7rNiPnxKt1+GVXzesHPuVTF8oWUy4hSqRIMfZBgJssWsBO1U8uJzyNd506txguIi/a2UW5k6IdNkblXuA+WSP+thep8Nsi8rGyiQNmPjen6YQnlcmAMUNnimtvX4nG0RFdrpy0s0gv+1oMKFQ3V7KuP3JbyY4HmWLx6UD8XeLBjkP4OvB4gWbL33529fRfA03oLjHyqlIpOwOwo1qZY2bxdmTio35gr7X4A+VkefDkeaf+9vSNEHwv0IG8CorPrMf4GxG2CHlfARxFvG/058eNjYgcYnTKReda0QVWwTs1rc1h5xRd5jlt8k3P+sHAk76FFa4PDNARClBoG4YWtY0Islz10Lp5K+wLpULTnbq7QO4eogp1+RtPdiBucxh0WMwt3rrxMe5XwkN6fdH/laVFxJMATq0NZEY8RZo8pVFT4=
